# Generated by Django 5.0.4 on 2024-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_uid'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='default_response',
            field=models.ManyToManyField(blank=True, related_name='default_response', to='questions.qustion'),
        ),
    ]
