# Generated by Django 5.0.4 on 2024-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_answer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
